# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grRRCpp_dense_nf <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB) {
    .Call('_grpRR_grRRCpp_dense_nf', PACKAGE = 'grpRR', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB)
}

grRRCpp_dense_ff <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init) {
    .Call('_grpRR_grRRCpp_dense_ff', PACKAGE = 'grpRR', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init)
}

grRRCpp_sparse_ff <- function(X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init) {
    .Call('_grpRR_grRRCpp_sparse_ff', PACKAGE = 'grpRR', X, y, annot, g, NoPerGroup, d_tau, r_tau, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init)
}

grpRRCpp_logistic_nf <- function(X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB) {
    .Call('_grpRR_grpRRCpp_logistic_nf', PACKAGE = 'grpRR', X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB)
}

grpRRCpp_logistic_ff <- function(X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init, intercept) {
    .Call('_grpRR_grpRRCpp_logistic_ff', PACKAGE = 'grpRR', X, y, annot, g, NoPerGroup, d_gamma, r_gamma, max_iter, th, calcELB, verbose, freqELB, mu_init, intercept)
}

grpRRCpp_sparse_logistic_ff <- function(X, y, annot, g, NoPerGroup, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init, intercept) {
    .Call('_grpRR_grpRRCpp_sparse_logistic_ff', PACKAGE = 'grpRR', X, y, annot, g, NoPerGroup, d_gamma, r_gamma, r_pi, d_pi, max_iter, th, calcELB, verbose, freqELB, mu_init, psi_init, intercept)
}

